openapi: 3.0.3
info:
  title: Advert Platform Backend
  version: 1.0.0
  description: >
    This is the official Advert Platform Backend API.
    Supports user registration, login, ad creation, ad retrieval, updating, and deleting.
    Login can be done using:
      - Email + Password
      - OR Username + Password
    Ad media can be external URLs (no direct file uploads).
servers:
  - url: https://advert-platform-backend.onrender.com
    description: Production Server
  - url: http://localhost:5000
    description: Development Server
tags:
  - name: Auth
    description: User Registration and Login
  - name: Ads
    description: Advertisement Operations
paths:
  /api/register:
    post:
      tags:
        - Auth
      summary: Register a new user
      description: |
        Registration required fields:
        - name
        - email
        - username
        - phoneNumber
        - password
        - role
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                name:
                  type: string
                email:
                  type: string
                username:
                  type: string
                phoneNumber:
                  type: string
                password:
                  type: string
                role:
                  type: string
      responses:
        "201":
          description: Registration successful
        "409":
          description: Conflict - Account already exists
  /api/login:
    post:
      tags:
        - Auth
      summary: Login
      description: |
        Login using either:
        - `email` + `password`, OR
        - `username` + `password`.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              oneOf:
                - type: object
                  required:
                    - email
                    - password
                  properties:
                    email:
                      description: User email
                      type: string
                      example: "john@example.com"
                    password:
                      description: User password
                      type: string
                      example: "pass123"
                - type: object
                  required:
                    - username
                    - password
                  properties:
                    username:
                      description: User username
                      type: string
                      example: "johnny"
                    password:
                      description: User password
                      type: string
                      example: "pass123"
      responses:
        "200":
          description: Login successful
        "400":
          description: Invalid email, username, or password


  /api/ads:
    get:
      tags:
        - Ads
      summary: Get All Ads
      description: Returns a list of available ads
      responses:
        "200":
          description: List of ads
    post:
      tags:
        - Ads
      summary: Create an Ad
      description: |
        Create an ad. Requires:
        - title, category, price, description
        - media: array of external URLs (e.g., images, videos)

        Example media URLs:
        - https://picsum.photos/200/300
        - https://www.example.com/myproduct.png
      requestBody:
        required: true
        content:
          application/json:
            schema:
              required:
                - title
                - category
                - price
                - description
              properties:
                title:
                  type: string
                category:
                  type: string
                price:
                  type: number
                description:
                  type: string
                media:
                  type: array
                  items:
                    type: string
            example:
              title: "Modern Lipstick"
              category: "Beauty Products"
              price: 29.99
              description: "A long-lasting matte lipstick."
              media:
                - "https://media.istockphoto.com/id/1277741500/photo/lipstick-product.png"
      responses:
        "201":
          description: Ad Created
        "400":
          description: Bad Request
  /api/ads/{id}:
    get:
      tags:
        - Ads
      summary: Get Ad By Id
      description: Returns a specific ad
      parameters:
        - in: path
          name: id
          required: true
      responses:
        "200":
          description: Returns the specific ad
        "404":
          description: Not Found
    put:
      tags:
        - Ads
      summary: Update Ad
      description: Requires authentication as the ad's vendor
      parameters:
        - in: path
          name: id
          required: true
      requestBody:
        content:
          application/json:
            schema:
              properties:
                title:
                  type: string
                category:
                  type: string
                price:
                  type: number
                description:
                  type: string
                media:
                  type: array
                  items:
                    type: string
      responses:
        "200":
          description: Ad updated
        "403":
          description: Not authorized to update this ad
    delete:
      tags:
        - Ads
      summary: Delete Ad
      description: Requires authentication as the ad's vendor
      parameters:
        - in: path
          name: id
          required: true
      responses:
        "200":
          description: Ad deleted
        "403":
          description: Not authorized to delete this ad
        "404":
          description: Not Found